# Generated by Django 5.1.1 on 2024-12-15 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=8,
                        validators=[django.core.validators.MinValueValidator(8)],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "department",
                    models.CharField(
                        max_length=4,
                        validators=[django.core.validators.MinValueValidator(4)],
                    ),
                ),
                ("professor", models.CharField(max_length=100)),
                ("keywords", models.TextField(blank=True)),
                (
                    "corequisites",
                    models.ManyToManyField(
                        blank=True, to="amherst_coursework_algo.course"
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True, to="amherst_coursework_algo.course"
                    ),
                ),
            ],
        ),
    ]
