# Generated by Django 5.1.4 on 2025-02-07 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amherst_coursework_algo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Keyword",
                "verbose_name_plural": "Keywords",
                "ordering": ["value"],
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="overGuidelines",
        ),
        migrations.RemoveField(
            model_name="prerequisites",
            name="placement_course",
        ),
        migrations.RemoveField(
            model_name="prerequisites",
            name="recommended_courses",
        ),
        migrations.RemoveField(
            model_name="prerequisites",
            name="required_courses",
        ),
        migrations.RemoveField(
            model_name="course",
            name="prerequisites",
        ),
        migrations.RemoveField(
            model_name="course",
            name="department",
        ),
        migrations.AddField(
            model_name="course",
            name="courseMaterialsLink",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="departments",
            field=models.ManyToManyField(
                related_name="courses", to="amherst_coursework_algo.department"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, help_text="Text description of prerequisites"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="enrollmentText",
            field=models.TextField(
                default="Contact the professor for enrollment details."
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="freshmanCap",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="juniorCap",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="overallCap",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="placement_course",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="prefForMajor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="professor_override",
            field=models.BooleanField(
                default=False, help_text="Can professor override prerequisites?"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="recommended_courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="recommended_for",
                to="amherst_coursework_algo.course",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="required_courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="required_for",
                to="amherst_coursework_algo.prerequisiteset",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="seniorCap",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="sophomoreCap",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coursecode",
            name="value",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.MaxLengthValidator(9),
                ],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="divisions",
            field=models.ManyToManyField(
                related_name="courses", to="amherst_coursework_algo.division"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="keywords",
            field=models.ManyToManyField(
                related_name="courses", to="amherst_coursework_algo.keyword"
            ),
        ),
        migrations.DeleteModel(
            name="OverGuidelines",
        ),
        migrations.DeleteModel(
            name="Prerequisites",
        ),
    ]
