# Generated by Django 5.1.1 on 2024-12-15 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amherst_coursework_algo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="credit_hours",
            field=models.IntegerField(
                default=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="enrollment_limit",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="how_to_handle_overenrollment",
            field=models.TextField(null=True),
        ),
    ]
