# Generated by Django 5.1.4 on 2025-03-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amherst_coursework_algo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"verbose_name": "Section", "verbose_name_plural": "Sections"},
        ),
        migrations.RemoveField(
            model_name="section",
            name="days",
        ),
        migrations.RemoveField(
            model_name="section",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="section",
            name="start_time",
        ),
        migrations.AddField(
            model_name="section",
            name="friday_end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="friday_start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="monday_end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="monday_start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="saturday_end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="saturday_start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="sunday_end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="sunday_start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="thursday_end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="thursday_start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="tuesday_end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="tuesday_start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="wednesday_end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="wednesday_start_time",
            field=models.TimeField(null=True),
        ),
    ]
