# Generated by Django 5.1.4 on 2025-02-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "amherst_coursework_algo",
            "0002_division_keyword_remove_course_overguidelines_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="courseCodes",
            field=models.ManyToManyField(
                related_name="courses", to="amherst_coursework_algo.coursecode"
            ),
        ),
    ]
