# Generated by Django 5.1.4 on 2025-02-09 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amherst_coursework_algo", "0003_alter_course_coursecodes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="sections",
        ),
        migrations.AlterField(
            model_name="course",
            name="courseLink",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="courseMaterialsLink",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="placement_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="amherst_coursework_algo.course",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="myCourse",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="amherst_coursework_algo.course",
            ),
        ),
    ]
