# Generated by Django 5.1.4 on 2025-01-28 21:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "amherst_coursework_algo",
            "0003_coursecode_department_overguidelines_professor_year_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="overguidelines",
            old_name="sophCap",
            new_name="sophomoreCap",
        ),
        migrations.AddField(
            model_name="course",
            name="courseDescription",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="overguidelines",
            name="myCourse",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="amherst_coursework_algo.course",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="myCourse",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_sections",
                to="amherst_coursework_algo.course",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="section_number",
            field=models.IntegerField(
                default=1,
                help_text="Section number",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
        ),
        migrations.RemoveField(
            model_name="course",
            name="overGuidelines",
        ),
        migrations.AlterField(
            model_name="professor",
            name="link",
            field=models.URLField(
                blank=True, help_text="Link to professor's page", null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("myCourse", "section_number")},
        ),
        migrations.AddField(
            model_name="course",
            name="overGuidelines",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="amherst_coursework_algo.overguidelines",
            ),
        ),
    ]
