from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "amherst_coursework_algo",
            "0004_alter_course_corequisites_alter_course_coursecodes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="One-sentence course summary generated by AI.",
            ),
        ),
    ]


