# Generated by Django 5.1.4 on 2025-02-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("amherst_coursework_algo", "0005_rename_description_course_prereqdescription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="keyword",
            options={
                "ordering": ["name"],
                "verbose_name": "Keyword",
                "verbose_name_plural": "Keywords",
            },
        ),
        migrations.RenameField(
            model_name="keyword",
            old_name="value",
            new_name="name",
        ),
    ]
