name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Match the Python version

      # Install dependencies including Django and Sphinx
      - name: Install dependencies
        working-directory: ./docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Add an optional command to ensure dependencies are installed correctly
      - name: Check Django Installation
        run: python -c "import django; print(django.get_version())"

      # Build the HTML using Sphinx
      - name: Build HTML
        run: |
          cd docs
          make html

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/build/html/

      # Deploy the documentation using GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
